# Generated by Django 4.1.1 on 2022-09-13 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=300)),
                ('lasname', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schoolName', models.CharField(max_length=500)),
                ('level_of_school', models.CharField(max_length=150)),
                ('started_year', models.CharField(max_length=150)),
                ('finished_year', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='MySkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skillname', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PersonalSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skillname', models.CharField(max_length=700)),
                ('skill_in_percent', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_title', models.CharField(max_length=150)),
                ('project_type', models.CharField(max_length=150)),
                ('project_images', models.CharField(max_length=150)),
                ('project_link', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='ProfessionalSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skillname', models.CharField(max_length=700)),
                ('skill_in_percent', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SocialmediaLinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('socialMediaName', models.CharField(max_length=150)),
                ('link', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Tools',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tool_name', models.CharField(max_length=200)),
                ('used_for', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('personalSkill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolioapp.personalskill')),
                ('professionalSkill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolioapp.professionalskill')),
            ],
        ),
        migrations.CreateModel(
            name='AboutME',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('photo1', models.ImageField(upload_to='')),
                ('photo2', models.ImageField(upload_to='')),
                ('mySkill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolioapp.myskill')),
                ('socialmediaLinks', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolioapp.socialmedialinks')),
            ],
        ),
    ]
