# Generated by Django 4.1.1 on 2022-09-13 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioapp', '0003_alter_aboutme_options_alter_contactme_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutme',
            name='socialmediaLinks',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='portfolioapp.socialmedialinks'),
        ),
        migrations.AlterField(
            model_name='skills',
            name='personalSkill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='portfolioapp.personalskill'),
        ),
        migrations.AlterField(
            model_name='skills',
            name='professionalSkill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='portfolioapp.professionalskill'),
        ),
    ]
