# Generated by Django 4.1.1 on 2022-09-13 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioapp', '0004_alter_aboutme_socialmedialinks_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutme',
            name='description',
            field=models.CharField(default='', max_length=2000),
        ),
        migrations.AlterField(
            model_name='aboutme',
            name='mySkill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='portfolioapp.myskill'),
        ),
    ]
