# Generated by Django 4.1.1 on 2022-09-28 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioapp', '0006_department_employe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutme',
            name='mySkill',
        ),
        migrations.RemoveField(
            model_name='aboutme',
            name='socialmediaLinks',
        ),
        migrations.RemoveField(
            model_name='skills',
            name='personalSkill',
        ),
        migrations.RemoveField(
            model_name='skills',
            name='professionalSkill',
        ),
    ]
