# Generated by Django 4.1.1 on 2022-09-28 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioapp', '0007_remove_aboutme_myskill_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='myskill',
            name='aboutme',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='portfolioapp.aboutme'),
        ),
        migrations.AddField(
            model_name='socialmedialinks',
            name='aboutme',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='portfolioapp.aboutme'),
        ),
    ]
