# Generated by Django 4.1.1 on 2022-09-28 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioapp', '0008_myskill_aboutme_socialmedialinks_aboutme'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employe',
            name='department',
        ),
        migrations.DeleteModel(
            name='Skills',
        ),
        migrations.DeleteModel(
            name='Department',
        ),
        migrations.DeleteModel(
            name='Employe',
        ),
    ]
