# Generated by Django 4.1.1 on 2022-09-28 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioapp', '0009_remove_employe_department_delete_skills_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactme',
            old_name='lasname',
            new_name='lastname',
        ),
        migrations.AddField(
            model_name='contactme',
            name='email',
            field=models.EmailField(blank=True, max_length=70, unique=True),
        ),
        migrations.AddField(
            model_name='contactme',
            name='message',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='aboutme',
            name='photo1',
            field=models.ImageField(upload_to='ProfileImages'),
        ),
        migrations.AlterField(
            model_name='aboutme',
            name='photo2',
            field=models.ImageField(upload_to='ProfileImages'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='project_images',
            field=models.ImageField(upload_to='PortfolioImages'),
        ),
    ]
