# Generated by Django 4.1.1 on 2022-10-01 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioapp', '0010_rename_lasname_contactme_lastname_contactme_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myskill',
            name='aboutme',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='myskills', to='portfolioapp.aboutme'),
        ),
        migrations.AlterField(
            model_name='socialmedialinks',
            name='aboutme',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mysoicialmedialinks', to='portfolioapp.aboutme'),
        ),
    ]
